name: Run all TypeScript compiler commands

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    
    - name: npm install for the whole project
      run: cd src && npm install

    - name: npm install for client code
      run: cd src/client && npm install

    - name: npm install for the server
      run: cd src/server && npm install
    
    - name: tsc
      uses: icrawl/action-tsc@v1
      with:
        project: src
